# Generated by Django 6.1.1 on 2026-09-11 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('client_uuid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('customer', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='BORRADOR', max_length=32)),
                ('synthetic', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedVisit',
            fields=[
                ('planned_uuid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('site_id', models.CharField(blank=True, default='', max_length=255)),
                ('date_label', models.CharField(blank=True, default='', max_length=32)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(blank=True, default='planned', max_length=32)),
                ('synthetic', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structured_json', models.JSONField(blank=True, null=True)),
                ('confidence_map', models.JSONField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, default='', max_length=32)),
                ('provenance', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='api.inspection')),
            ],
        ),
    ]
