/**
 * QVAC SDK Worker Entry (auto-generated)
 * Generated by: @qvac/sdk/commands bundleSdk
 * Plugins: 5
 *
*   - @qvac/sdk/llamacpp-completion/plugin
*   - @qvac/sdk/llamacpp-embedding/plugin
*   - @qvac/sdk/nmtcpp-translation/plugin
*   - @qvac/sdk/ggml-ocr/plugin
*   - @qvac/sdk/parakeet-transcription/plugin
 */

import { initializeWorker, ensureRPCSetup } from "@qvac/sdk/worker-lifecycle";
import { registerPlugin } from "@qvac/sdk/plugins";
import { getServerLogger } from "@qvac/sdk/logging";

import { llmPlugin } from "@qvac/sdk/llamacpp-completion/plugin";
import { embeddingsPlugin } from "@qvac/sdk/llamacpp-embedding/plugin";
import { nmtPlugin } from "@qvac/sdk/nmtcpp-translation/plugin";
import { ocrPlugin } from "@qvac/sdk/ggml-ocr/plugin";
import { parakeetPlugin } from "@qvac/sdk/parakeet-transcription/plugin";

const { hasRPCConfig } = initializeWorker();

const logger = getServerLogger();
logger.info("🐻 QVAC Worker (custom bundle)");
logger.info("📦 Plugins: 5");

registerPlugin(llmPlugin);
registerPlugin(embeddingsPlugin);
registerPlugin(nmtPlugin);
registerPlugin(ocrPlugin);
registerPlugin(parakeetPlugin);

// Auto-setup RPC if config present
if (hasRPCConfig) {
  ensureRPCSetup();
}
