// ChatCaptureScreen — SCREEN_01 + F01/F02 chat loop (conversational).
// The visible reply is ALWAYS generated by MedPsy-1.7B (conversation.ts)
// with full recent history + photo context — never a fixed template.
// JSON structuring (structure.ts) runs hidden underneath for ReviewScreen.
// Photos render inline + gallery strip + fullscreen. Voice fills the
// composer as an editable draft with honest error messages in-chat.

import React, { useEffect, useRef, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TextInput, TouchableOpacity, ActivityIndicator, Alert, Image, KeyboardAvoidingView, Keyboard, Platform, Modal, Pressable } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as FileSystem from 'expo-file-system';
import { Audio } from 'expo-av';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Disclaimer } from '../components/atoms';
import { useTheme } from '../../theme/ThemeContext';
import { useThemedStyles } from '../../theme/useThemedStyles';
import type { ThemeTokens } from '../../theme/tokens';
import { Icon } from '../components/Icon';
import { WizardHeader } from '../components/WizardHeader';
import { useApp } from '../state/AppState';
import { useStrings } from '../i18n/useStrings';
import { getMessages, appendMessage, savePhotoEvidence, type ChatMsg } from '../db/database';
import { normalizeToEnglish } from '../qvac/translate';
import { describePhoto, readLabelText } from '../qvac/visionOcr';
import { structureEntities, lastStructureError, type StructuredReport } from '../qvac/structure';
import { generateAssistantReply, type DialogueTurn } from '../qvac/conversation';
import { matchCatalog } from '../catalog/catalog';
import { transcribeAudio } from '../qvac/voice';

function buildPhotoSummary(vision: { modality_guess: string | null; manufacturer_guess: string | null; model_guess: string | null; label_text_free: string | null }, ocrText: string): string {
  const parts: string[] = [];
  parts.push(`modalidad ${vision.modality_guess ?? 'no clara'}`);
  if (vision.manufacturer_guess) parts.push(`marca aparente ${vision.manufacturer_guess}`);
  if (vision.model_guess) parts.push(`modelo aparente ${vision.model_guess}`);
  if (ocrText.trim()) parts.push(`placa: "${ocrText.trim().slice(0, 200)}"`);
  else if (vision.label_text_free) parts.push(`vista: "${vision.label_text_free.slice(0, 200)}"`);
  else parts.push('sin texto legible');
  return parts.join(', ');
}

function turnsFromMessages(msgs: ChatMsg[]): DialogueTurn[] {
  return msgs.slice(-8).map((m) => ({
    role: m.role,
    text: m.photo_ref ? `${m.text_original} [foto adjunta]` : m.text_original,
    photoSummary: null,
  }));
}

export default function ChatCaptureScreen({ inspectionId }: { inspectionId: string }) {
  const { setWizard, setDetailsOpen, tier } = useApp();
  const t = useStrings();
  const { theme: th } = useTheme();
  const s = useThemedStyles(makeStyles);
  const insets = useSafeAreaInsets();
  const [msgs, setMsgs] = useState<ChatMsg[]>([]);
  const [input, setInput] = useState('');
  const [busy, setBusy] = useState<string | null>(null);
  const [authorized, setAuthorized] = useState(false);
  const [recording, setRecording] = useState<Audio.Recording | null>(null);
  const [recSecs, setRecSecs] = useState(0);
  const [selectedPhoto, setSelectedPhoto] = useState<string | null>(null);
  const [kbHeight, setKbHeight] = useState(0);
  const scroll = useRef<ScrollView>(null);
  const recTimer = useRef<ReturnType<typeof setInterval> | null>(null);
  const recStart = useRef<number>(0);

  const reload = async () => setMsgs(await getMessages(inspectionId).catch(() => []));
  useEffect(() => {
    reload();
    (async () => {
      const cur = await getMessages(inspectionId).catch(() => []);
      if (cur.length === 0) {
        const hello: ChatMsg = { role: 'assistant', text_original: 'Soy tu asistente de inventario. Cuéntame con tus palabras qué equipos de imagen viste — modalidad, marca, cantidad, edad aproximada — o mándame una foto de la placa y la analizamos juntos.', lang: null, text_en: null };
        await appendMessage(inspectionId, hello);
        reload();
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [inspectionId]);

  useEffect(() => { setTimeout(() => scroll.current?.scrollToEnd({ animated: true }), 100); }, [msgs]);

  useEffect(() => {
    const show = Keyboard.addListener('keyboardDidShow', (e) => {
      setKbHeight(e.endCoordinates.height);
      setTimeout(() => scroll.current?.scrollToEnd({ animated: true }), 50);
    });
    const hide = Keyboard.addListener('keyboardDidHide', () => setKbHeight(0));
    return () => { show.remove(); hide.remove(); recTimer.current && clearInterval(recTimer.current); };
  }, []);

  const push = async (m: ChatMsg) => {
    await appendMessage(inspectionId, m);
    await reload();
  };

  const runAssistantTurn = async (opts: {
    userText: string;
    textEn: string;
    lang: 'es' | 'pt';
    untranslated: boolean;
    baseTurns: DialogueTurn[];
    photoSummary?: string | null;
  }) => {
    // Hidden structuring pass (feeds ReviewScreen + dialogue facts).
    setBusy('Anotando equipos…');
    let struct: StructuredReport | null = null;
    let structMethod = 'regex-fallback';
    try {
      const rep = await structureEntities({
        text_en: opts.photoSummary ? `${opts.textEn}\nPhoto evidence: ${opts.photoSummary}` : opts.textEn,
      });
      struct = rep;
      structMethod = (rep.confidence_map as any)?.fallback ? 'regex-fallback' : 'MedPsy-1.7B Q4_K_M';
    } catch {
      struct = null;
    }
    const match = matchCatalog(opts.textEn);
    const catalogHint = match.entry
      ? `${match.entry.modality} ${match.entry.family}: placa en ${match.entry.point_of_interest[0]}; conviene preguntar: ${match.entry.staff_question[0]}`
      : null;
    // Visible conversational pass — the actual AI reply.
    setBusy('Pensando…');
    const { reply } = await generateAssistantReply({
      turns: opts.baseTurns,
      latestUserEn: opts.textEn,
      latestUserOriginal: opts.userText,
      untranslated: opts.untranslated,
      structured: struct,
      structuredMethod: structMethod,
      photoSummary: opts.photoSummary ?? null,
      catalogHint,
      modelError: lastStructureError(),
    });
    await push({ role: 'assistant', text_original: reply, lang: opts.lang, text_en: null });
  };

  const sendText = async (override?: string) => {
    const text = (override ?? input).trim();
    if (!text || busy || recording) return;
    setInput('');
    Keyboard.dismiss();
    await push({ role: 'user', text_original: text, lang: null, text_en: null });
    const baseTurns = turnsFromMessages([...msgs, { role: 'user' as const, text_original: text, lang: null, text_en: null }]);
    try {
      setBusy('Traduciendo…');
      const { text_en, lang, untranslated } = await normalizeToEnglish({ text });
      await runAssistantTurn({ userText: text, textEn: text_en, lang, untranslated, baseTurns });
    } catch {
      await push({ role: 'assistant', text_original: 'Guardé tu mensaje localmente. Sin conexión sigo anotando — cuéntame un poco más o revisamos al final.', lang: null, text_en: null });
    } finally {
      setBusy(null);
    }
  };

  const takePhoto = async () => {
    if (busy || recording) return;
    if (!authorized) {
      Alert.alert('Foto autorizada', 'Confirma que el sitio autoriza fotografiar la placa del equipo.', [
        {
          text: 'No autorizado',
          style: 'cancel',
          onPress: async () => {
            await push({ role: 'assistant', text_original: 'Sin problema, seguimos sin foto. Descríbeme los equipos: ¿qué modalidad, qué marca se lee, cuántos son?', lang: null, text_en: null });
          },
        },
        {
          text: 'Autorizada',
          onPress: () => {
            setAuthorized(true);
            openCameraFlow();
          },
        },
      ]);
      return;
    }
    openCameraFlow();
  };

  const openCameraFlow = async () => {
    if (busy || recording) return;
    const perm = await ImagePicker.requestCameraPermissionsAsync();
    if (!perm.granted) {
      await push({ role: 'assistant', text_original: 'Sin permiso de cámara seguimos con texto — descríbeme la placa: marca, modelo y lo que se lea.', lang: null, text_en: null });
      return;
    }
    const shot = await ImagePicker.launchCameraAsync({ quality: 0.8, base64: false });
    if (shot.canceled || !shot.assets?.[0]?.uri) return;
    try {
      const src = shot.assets[0].uri;
      const dst = `${(FileSystem as any).documentDirectory}cibi/media/photos/${inspectionId}-${Date.now()}.jpg`;
      await FileSystem.makeDirectoryAsync(`${(FileSystem as any).documentDirectory}cibi/media/photos`, { intermediates: true }).catch(() => {});
      await FileSystem.copyAsync({ from: src, to: dst }).catch(() => {});
      const path = await FileSystem.getInfoAsync(dst).then((i) => (i.exists ? dst : src)).catch(() => src);
      // Show the photo immediately so it never feels lost.
      await push({ role: 'user', text_original: 'Foto de placa', lang: null, text_en: null, photo_ref: path });
      // Sequential: vision first, then OCR (one model resident at a time).
      setBusy('Viendo la foto…');
      const vision = await describePhoto({ photoPath: path });
      setBusy('Leyendo la placa…');
      const ocrRes = await readLabelText({ photoPath: path });
      await savePhotoEvidence(inspectionId, path, true, ocrRes.blocks, vision);
      const summary = buildPhotoSummary(vision, ocrRes.joinedText);
      const ocrEn = ocrRes.joinedText.trim();
      const textEn = ocrEn || vision.raw || vision.label_text_free || 'photo of imaging equipment plate';
      const baseTurns = turnsFromMessages([...msgs, { role: 'user' as const, text_original: 'Foto de placa [foto adjunta]', lang: null, text_en: null }]);
      await runAssistantTurn({
        userText: `Te mandé una foto de la placa. ${summary}`,
        textEn,
        lang: 'es',
        untranslated: false,
        baseTurns,
        photoSummary: summary,
      });
    } catch {
      await push({ role: 'assistant', text_original: 'La foto quedó guardada como evidencia pero no pude analizarla en el teléfono. Descríbeme lo que dice la placa y seguimos.', lang: null, text_en: null });
    } finally {
      setBusy(null);
    }
  };

  const recordingOptions = (): Audio.RecordingOptions => {
    if (Platform.OS === 'ios') {
      return {
        android: undefined as any,
        ios: {
          extension: '.wav',
          outputFormatIOS: Audio.IOSOutputFormat.LINEARPCM,
          audioQuality: Audio.IOSAudioQuality.HIGH,
          sampleRate: 16000,
          numberOfChannels: 1,
          bitRate: 256000,
          linearPCMBitDepth: 16,
          linearPCMIsBigEndian: false,
          linearPCMIsFloat: false,
        } as any,
        web: undefined as any,
      } as unknown as Audio.RecordingOptions;
    }
    // Android MediaRecorder has no WAV output: 16kHz mono AAC in .m4a,
    // which the on-device decoder resamples for Parakeet.
    return {
      android: {
        extension: '.m4a',
        outputFormat: Audio.AndroidOutputFormat.MPEG_4,
        audioEncoder: Audio.AndroidAudioEncoder.AAC,
        sampleRate: 16000,
        numberOfChannels: 1,
        bitRate: 64000,
      },
      ios: undefined as any,
      web: undefined as any,
    } as unknown as Audio.RecordingOptions;
  };

  const toggleRecord = async () => {
    try {
      if (recording) {
        recTimer.current && clearInterval(recTimer.current);
        const secs = (Date.now() - recStart.current) / 1000;
        setBusy('Transcribiendo voz…');
        await recording.stopAndUnloadAsync();
        const uri = recording.getURI();
        setRecording(null);
        setRecSecs(0);
        if (!uri || secs < 1) {
          setBusy(null);
          await push({ role: 'assistant', text_original: 'La grabación fue muy corta — mantén el micrófono al menos un segundo y dicta de nuevo, o escribe el reporte.', lang: null, text_en: null });
          return;
        }
        const dst = `${(FileSystem as any).documentDirectory}cibi/media/audio/${inspectionId}-${Date.now()}${Platform.OS === 'ios' ? '.wav' : '.m4a'}`;
        await FileSystem.makeDirectoryAsync(`${(FileSystem as any).documentDirectory}cibi/media/audio`, { intermediates: true }).catch(() => {});
        await FileSystem.copyAsync({ from: uri, to: dst }).catch(() => {});
        const audioPath = await FileSystem.getInfoAsync(dst).then((i) => (i.exists ? dst : uri)).catch(() => uri);
        const { text, ok, error } = await transcribeAudio({ audioPath });
        setBusy(null);
        if (ok) {
          setInput(text);
          await push({ role: 'assistant', text_original: `Te escuché: "${text.slice(0, 200)}". Revísalo en el cuadro, edítalo si hace falta y envíalo.`, lang: null, text_en: null });
        } else {
          await push({ role: 'assistant', text_original: `No pude transcribir el audio en el teléfono (${error ?? 'fallo de modelo'}). El audio quedó guardado — escribe el reporte y seguimos sin problema.`, lang: null, text_en: null });
        }
        return;
      }
      const perm = await Audio.requestPermissionsAsync();
      if (!perm.granted) {
        Alert.alert('Micrófono', 'Sin permiso — escribe el reporte, el flujo no se bloquea.');
        return;
      }
      await Audio.setAudioModeAsync({ allowsRecordingIOS: true, playsInSilentModeIOS: true });
      const rec = new Audio.Recording();
      await rec.prepareToRecordAsync(recordingOptions());
      await rec.startAsync();
      recStart.current = Date.now();
      setRecording(rec);
      setRecSecs(0);
      recTimer.current = setInterval(() => setRecSecs(Math.floor((Date.now() - recStart.current) / 1000)), 500);
    } catch {
      recTimer.current && clearInterval(recTimer.current);
      setRecording(null);
      setRecSecs(0);
      setBusy(null);
      await push({ role: 'assistant', text_original: 'No pude iniciar la grabación en este teléfono. Usa el teclado — el texto lleva la inspección.', lang: null, text_en: null });
    }
  };

  const galleryPhotos = msgs.filter((m) => m.photo_ref).map((m) => m.photo_ref as string);

  return (
    <KeyboardAvoidingView
      style={s.wrap}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      keyboardVerticalOffset={Platform.OS === 'ios' ? insets.top + 56 : 0}
    >
      <WizardHeader
        title={t.wizardStep1}
        onBack={() => setWizard(null)}
        right={
          <TouchableOpacity
            style={s.reviewBtn}
            onPress={() => setWizard({ name: 'review', inspectionId })}
            accessibilityRole="button"
            accessibilityLabel={t.reviewAction}
            hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
          >
            <Icon name="review" size={16} color={th.onAccent} />
            <Text style={s.reviewBtnText}>{t.reviewAction}</Text>
          </TouchableOpacity>
        }
      />
      <View style={s.tierbar}>
        {(['CIBI', 'CIBI_PRO', 'CIBI_SUPER'] as const).map((tt) => (
          <View key={tt} style={[s.tier, tt === 'CIBI' && s.tierOn]}>
            <View style={s.tierRow}>
              <View style={[s.dot, tt === 'CIBI' ? s.dotGreen : tt === 'CIBI_PRO' ? s.dotBlue : s.dotPurple]} />
              <Text style={s.tierText}>{tt === 'CIBI' ? 'CIBI' : tt === 'CIBI_PRO' ? 'CIBI Pro' : 'CIBI Super'}{tt !== 'CIBI' ? ' · ' : ''}</Text>
              {tt !== 'CIBI' ? <Icon name="close" size={12} color={th.muted} /> : null}
            </View>
          </View>
        ))}
      </View>
      <ScrollView
        ref={scroll}
        style={s.chat}
        contentContainerStyle={{ gap: 12, paddingBottom: 12 + insets.bottom }}
        keyboardShouldPersistTaps="handled"
      >
        {msgs.map((m, i) => (
          <View key={i} style={[s.bubble, m.role === 'user' ? s.user : s.ai]}>
            {m.photo_ref ? (
              <Pressable onPress={() => setSelectedPhoto(m.photo_ref as string)}>
                <Image source={{ uri: m.photo_ref }} style={s.photo} resizeMode="cover" />
                <Text style={s.meta}>Toca para ampliar</Text>
              </Pressable>
            ) : null}
            <Text style={s.msgText}>{m.text_original}</Text>
            {m.role === 'user' && m.text_en ? <Text style={s.meta}>ES/PT detectado → EN guardado</Text> : null}
            {m.role === 'assistant' ? <Text style={s.meta}>{tier} · en tu teléfono · <Text onPress={() => setDetailsOpen(true)} style={{ textDecorationLine: 'underline' }}>detalles</Text></Text> : null}
          </View>
        ))}
        {busy ? <View style={[s.bubble, s.ai]}><ActivityIndicator color={th.green} /><Text style={s.meta}>{busy} (modelo on-device, uno a la vez)</Text></View> : null}
        {recording ? <View style={[s.bubble, s.ai]}><Text style={s.recText}>● Grabando {recSecs}s — habla ahora. Toca ■ para transcribir.</Text></View> : null}
        <Disclaimer />
      </ScrollView>
      {galleryPhotos.length > 0 ? (
        <ScrollView horizontal style={s.gallery} contentContainerStyle={{ gap: 8, paddingHorizontal: 12 }} showsHorizontalScrollIndicator={false}>
          {galleryPhotos.map((uri, i) => (
            <Pressable key={`${i}-${uri}`} onPress={() => setSelectedPhoto(uri)}>
              <Image source={{ uri }} style={s.thumb} resizeMode="cover" />
            </Pressable>
          ))}
        </ScrollView>
      ) : null}
      <View style={[s.composer, { paddingBottom: kbHeight > 0 ? kbHeight + 8 : Math.max(insets.bottom, 10) }]}>
        <View style={s.wabar}>
          <View style={s.inputwrap}>
            <TextInput style={s.input} placeholder={t.chatPlaceholder} placeholderTextColor={th.muted} value={input} onChangeText={setInput} multiline />
            <TouchableOpacity onPress={takePhoto} style={s.iconBtn} accessibilityRole="button" hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}><Icon name="camera" size={20} color={th.muted} /></TouchableOpacity>
            <TouchableOpacity onPress={toggleRecord} style={s.iconBtn} accessibilityRole="button" hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}><Icon name={recording ? 'stop' : 'mic'} size={20} color={recording ? th.amber : th.muted} /></TouchableOpacity>
          </View>
          <TouchableOpacity style={s.send} onPress={() => sendText()} accessibilityRole="button" disabled={!input.trim() || !!busy || !!recording}><Icon name="send" size={20} color={th.onAccent} /></TouchableOpacity>
        </View>
      </View>
      <Modal visible={!!selectedPhoto} transparent animationType="fade" onRequestClose={() => setSelectedPhoto(null)}>
        <Pressable style={s.viewer} onPress={() => setSelectedPhoto(null)}>
          {selectedPhoto ? <Image source={{ uri: selectedPhoto }} style={s.full} resizeMode="contain" /> : null}
          <Text style={s.viewerHint}>Toca para cerrar</Text>
        </Pressable>
      </Modal>
    </KeyboardAvoidingView>
  );
}

const makeStyles = (t: ThemeTokens) => StyleSheet.create({
  wrap: { flex: 1 },
  reviewBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: t.green, borderRadius: 12, paddingVertical: 10, paddingHorizontal: 12, minHeight: 44 },
  reviewBtnText: { color: t.onAccent, fontWeight: '800', fontSize: 13 },
  tierbar: { flexDirection: 'row', gap: 6, padding: 10 },
  tier: { flex: 1, borderRadius: 12, padding: 7, borderWidth: 1, borderColor: t.border, backgroundColor: t.surface },
  tierOn: { borderColor: t.green, backgroundColor: 'rgba(34,197,94,.12)' },
  tierText: { color: t.text, fontSize: 10.5, fontWeight: '700', textAlign: 'center' },
  tierRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 },
  dot: { width: 8, height: 8, borderRadius: 4 },
  dotGreen: { backgroundColor: t.green },
  dotBlue: { backgroundColor: t.blue },
  dotPurple: { backgroundColor: t.purple },
  chat: { flex: 1, paddingHorizontal: 16 },
  bubble: { maxWidth: '88%', borderRadius: 16, padding: 12 },
  ai: { backgroundColor: t.surface, borderColor: t.border, borderWidth: 1, alignSelf: 'flex-start' },
  user: { backgroundColor: 'rgba(59,130,246,.18)', borderColor: 'rgba(59,130,246,.5)', borderWidth: 1, alignSelf: 'flex-end' },
  msgText: { color: t.text, fontSize: 13.5, lineHeight: 20 },
  meta: { color: t.muted, fontSize: 11, marginTop: 6 },
  recText: { color: t.amber, fontSize: 13, fontWeight: '700' },
  photo: { width: 220, height: 160, borderRadius: 10, marginBottom: 8, backgroundColor: t.border },
  gallery: { maxHeight: 64, borderTopColor: t.border, borderTopWidth: 1, paddingVertical: 6 },
  thumb: { width: 56, height: 48, borderRadius: 8, backgroundColor: t.border, borderWidth: 1, borderColor: t.border },
  viewer: { flex: 1, backgroundColor: 'rgba(0,0,0,.92)', justifyContent: 'center', alignItems: 'center', gap: 12 },
  full: { width: '92%', height: '75%' },
  viewerHint: { color: '#fff', fontSize: 12 },
  composer: { borderTopColor: t.border, borderTopWidth: 1, backgroundColor: t.bg, padding: 10 },
  wabar: { flexDirection: 'row', gap: 8, alignItems: 'flex-end' },
  inputwrap: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: t.surface, borderColor: t.border, borderWidth: 1, borderRadius: 26, paddingLeft: 14, minHeight: 52 },
  input: { flex: 1, color: t.text, fontSize: 14, maxHeight: 110 },
  iconBtn: { padding: 10, minWidth: 44, minHeight: 44, justifyContent: 'center', alignItems: 'center' },
  send: { width: 52, height: 52, borderRadius: 26, backgroundColor: t.green, justifyContent: 'center', alignItems: 'center' },
});
